# Generated by Django 4.0.5 on 2022-08-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('Mech', 'Mech'), ('Civil', 'Civil')], max_length=5, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email_id1', models.CharField(max_length=100, null=True)),
                ('email_id2', models.CharField(max_length=100, null=True)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('tenth_board', models.CharField(max_length=15, null=True)),
                ('tenth_perc', models.FloatField(blank=True, null=True)),
                ('tenth_year', models.IntegerField(blank=True, null=True)),
                ('twelth_board', models.CharField(max_length=15, null=True)),
                ('twelth_perc', models.FloatField(blank=True, null=True)),
                ('twelth_year', models.IntegerField(blank=True, null=True)),
                ('diploma_board', models.CharField(max_length=15, null=True)),
                ('diploma_perc', models.FloatField(blank=True, null=True)),
                ('diploma_year', models.FloatField(blank=True, null=True)),
                ('sem1', models.FloatField(blank=True, null=True)),
                ('sem2', models.FloatField(blank=True, null=True)),
                ('sem3', models.FloatField(blank=True, null=True)),
                ('sem4', models.FloatField(blank=True, null=True)),
                ('sem5', models.FloatField(blank=True, null=True)),
                ('sem6', models.FloatField(blank=True, null=True)),
                ('cgpi', models.FloatField(blank=True, null=True)),
                ('perc', models.FloatField(blank=True, null=True)),
                ('live_kts', models.IntegerField(blank=True, null=True)),
                ('dead_kts', models.IntegerField(blank=True, null=True)),
                ('choice', models.CharField(choices=[('Placement', 'Placement'), ('Higher Studies', 'Higher Studies')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
