# Generated by Django 4.0.5 on 2022-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, null=True)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('offer1', models.CharField(max_length=100, null=True)),
                ('offer2', models.CharField(max_length=100, null=True)),
                ('offer3', models.CharField(max_length=100, null=True)),
                ('batch', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('Mech', 'Mech'), ('Civil', 'Civil')], max_length=5, null=True)),
                ('dob', models.DateField(null=True)),
                ('email_id1', models.CharField(max_length=100, null=True)),
                ('email_id2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone1', models.IntegerField(null=True)),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('tenth_board', models.CharField(max_length=15, null=True)),
                ('tenth_perc', models.FloatField(null=True)),
                ('tenth_year', models.IntegerField(null=True)),
                ('twelth_board', models.CharField(max_length=15, null=True)),
                ('twelth_perc', models.FloatField(null=True)),
                ('twelth_year', models.IntegerField(null=True)),
                ('diploma_board', models.CharField(blank=True, max_length=15, null=True)),
                ('diploma_perc', models.FloatField(blank=True, null=True)),
                ('diploma_year', models.FloatField(blank=True, null=True)),
                ('sem1', models.FloatField(blank=True, null=True)),
                ('sem2', models.FloatField(blank=True, null=True)),
                ('sem3', models.FloatField(null=True)),
                ('sem4', models.FloatField(null=True)),
                ('sem5', models.FloatField(null=True)),
                ('sem6', models.FloatField(null=True)),
                ('cgpi', models.FloatField(null=True)),
                ('perc', models.FloatField(null=True)),
                ('live_kts', models.IntegerField(blank=True, null=True)),
                ('dead_kts', models.IntegerField(blank=True, null=True)),
                ('choice', models.CharField(choices=[('Placement', 'Placement'), ('Higher Studies', 'Higher Studies')], max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=50, null=True),
        ),
    ]
