# Generated by Django 4.0.5 on 2022-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone1',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
