# Generated by Django 4.0.5 on 2022-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_students_cgpi_alter_students_diploma_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, null=True)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('offer1', models.CharField(max_length=100, null=True)),
                ('offer2', models.CharField(max_length=100, null=True)),
                ('offer3', models.CharField(max_length=100, null=True)),
                ('batch', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
