# Generated by Django 3.1.13 on 2023-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='file',
            field=models.FileField(upload_to='media/marksheets/'),
        ),
    ]
