# Generated by Django 4.0.5 on 2023-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230118_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='sem',
        ),
        migrations.AlterField(
            model_name='students',
            name='cgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem6',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
