# Generated by Django 4.0.5 on 2023-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_marks_branch_marks_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='sem',
            field=models.CharField(choices=[('I-II', 'I-II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=5, null=True),
        ),
    ]
